/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EffectType = { 'flash' : null } |
  { 'impact' : null } |
  { 'none' : null } |
  { 'zoom' : null } |
  { 'speed_lines' : null };
export type ExternalBlob = Uint8Array;
export interface Frame {
  'id' : string,
  'duration' : bigint,
  'order' : bigint,
  'textOverlays' : Array<TextOverlay>,
  'blobId' : ExternalBlob,
  'effectType' : EffectType,
}
export type OverlayStyle = { 'sfx' : null } |
  { 'normal' : null } |
  { 'shout' : null } |
  { 'bubble' : null };
export interface Project {
  'id' : string,
  'title' : string,
  'ownerId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'frames' : Array<Frame>,
}
export interface ProjectDTO {
  'id' : string,
  'title' : string,
  'description' : string,
  'frames' : Array<Frame>,
}
export interface ProjectMeta {
  'id' : string,
  'title' : string,
  'frameCount' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface TextOverlay {
  'x' : bigint,
  'y' : bigint,
  'text' : string,
  'style' : OverlayStyle,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[ProjectDTO], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[string], Project>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUserProjects' : ActorMethod<[], Array<ProjectMeta>>,
  'updateProject' : ActorMethod<[string, ProjectDTO], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];